### ISSUE TITLE
Port mopidy-local to Python 3

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy-local#12]
Tracking issue for the porting of this extension to Python 3.

**Comment by rdbhost** [comment]
The latest 3.0a2 installs mopidy-local as part of the setup.py.  It worked as-is on my local library.  So is there more to porting it than cleaning up the from __future__ lines, or putting it through 2to3?

Is it desirable to make the SQLite database the default db implementation, or to integrate cover images into that db?

**Comment by jodal** [comment]
Soon fixed by #10.

**Comment by jodal** [comment]
#10 has been merged, prerelease is soon out :-)
