### ISSUE TITLE
A proper home for `find_mtimes()`

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy-local#19]
[Moved from PR comment in #10.]

In Mopidy, `mopidy.internal.path.find_times()` is now a reexport of `mopidy.internal.mtimes.find_times()`. It is only used by `tests/audio/test_scan.py`. I think that we should either:

- conclude that the `mopidy.internal.mtimes` module belongs in Mopidy-Local and not Mopidy, or
- make `find_times()` a public method, maybe in the `mopidy.audio.scan` module?

@adamcik Any thoughts on the placement of the scanner and its supporting functions?

**Comment by adamcik** [comment]
I would err towards moving out. The find time stuff is all done for local's scanner at least, while I think the scanner might be used by e.g. the stream backend? If so we need to keep at least some of it mopidy.
