### ISSUE TITLE
Mopidy Local Scan crash 

### ISSUE THREAD

**Issue by gerroon** [mopidy/mopidy-local#23]
Local scan crashes.

https://paste.debian.net/hidden/2a73a099/

I am using Mopidy 2.10 on Debian Testing x64. I running it under my normal user.

**Comment by kingosticks** [comment]
Hi, I think https://github.com/mopidy/mopidy-local/commit/582e4bd26150ab0ae63e9ec9a76c17e3927512e8 should have fixed the crash but I am behind on getting a release cut. You may install from github in the meantime.

**Comment by kingosticks** [comment]
Fixed by https://github.com/mopidy/mopidy-local/pull/65
