### ISSUE TITLE
Build browse cache at scan time

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy-local#3]
Given the recent changes in the cache format we can now easily build it while scanning as we can add and remove things as we go. So the pre-built datastructure should be added to our json library file.

**Comment by jodal** [comment]
I'm not sure how well this issue translates to the SQLite backend, but I'm transferring the issue to the new Mopidy-Local extension so that the extension maintainers can take this into consideration.

**Comment by tkem** [comment]
Ahem... What are you guys talking about? What's the "browse cache"? Pardon my ignorance...
