### ISSUE TITLE
where is the SQLite database saved

### ISSUE THREAD

**Issue by sasgoose** [mopidy/mopidy-local#46]
Hi, 

I am using docker and local database seems to be blown away each time I restart. Where is the database located so that I can map this to my host machine and not lose it. 

Cheers

**Comment by sasgoose** [comment]
Found it! It was in /mnt/user/appdata/mopidy/custom-test/database/

**Comment by jodal** [comment]
I'll add some more detail for the next one finding this...

Mopidy-Local stores its database in a subdirectory named `local` (as in Mopidy-Local) in the directory pointed to by the the Mopidy configuration `core/data_dir`. Quoting the [`core/data_dir` docs](https://docs.mopidy.com/en/latest/config/#confval-core-data_dir):

> When running Mopidy as a regular user, this should usually be `$XDG_DATA_DIR/mopidy`, i.e. `~/.local/share/mopidy`.
>
> When running Mopidy as a system service, this should usually be `/var/lib/mopidy`.

In other words, the database will usually be at:

- `/home/me/.local/share/mopidy/local/library.db` if you run Mopidy from the terminal as your own user.
- `/var/lib/mopidy/local/library.db` if you run Mopidy as a system service, with the proper system-wide configuration in place, e.g. on Debian, Ubuntu, Raspbian, or Arch Linux.

The case we see here is a combination:

- `/var/lib/mopidy/.local/share/mopidy/local/library.db` if you run Mopidy as the `mopidy` user, which has `/var/lib/mopidy` as its homedir, *without* having properly set `core/data_dir` in the global Mopidy configuration.

**Comment by alirezadigi** [comment]
@jodal hi, thanks
How can I change these directories ( "/var/lib/mopidy/.local/share/mopidy/local/")??

**Comment by kingosticks** [comment]
By changing the config setting https://docs.mopidy.com/en/develop/config/#confval-core-data_dir
