### ISSUE TITLE
Doesn't Add any Music to Library

### ISSUE THREAD

**Issue by diabl0w** [mopidy/mopidy-local#51]
Not sure what the exact bug that is causing this is, but I can't get mopidy to add any of my music files to the library. I am running on a raspberry pi with the music being hosted on NFS that is mounted to raspberry pi in fstab. I can go into mopidy iris webui and see the music files when browsing "files" (/var/lib/mopidy/media"). However, when scanning for local media, it takes about an hour to scan the media directory (which only contains a few albums to begin with, so very poor performance) and then when its finished, it doesnt even add anything to the library. 

It is a brand new, fresh and extremely minimal setup, so I am not sure how no one else is having this issue. Config file:

> [core]
> data_dir = /var/lib/mopidy

> [audio]
> output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo

> [local]
> media_dir = /var/lib/mopidy/media

> [http]
> hostname = 0.0.0.0
> default_app = iris

> [mpd]
> hostname = 0.0.0.0

I do see this error in the logs: 
>  Error browsing local:directory?type=album: no such table: album
ERROR    2020-10-24 23:57:25,928 [6:LocalBackend-7] mopidy_local.library

Not sure why its not just creating the library table if thats all the issue is.
And also this error:

>   Lookup error for local:directory: Invalid lookup URI
ERROR    2020-10-25 00:11:45,650 [6:LocalBackend-7] mopidy_local.library

Once again, a fresh install, so I am not sure why all of these things are so misconfigured out of box

**Comment by diabl0w** [comment]
I think this is an issue with iris... closing

**Comment by bendschs** [comment]
same issue here, i don‘t  think this is because of iris, having the same with other web-clients and am not seeing any covers in local-webinterface.

cheers
bendsch

**Comment by tkem** [comment]
I guess the output of `mopidy local scan` might be somewhat helpful here...

**Comment by bendschs** [comment]
i tried "mopidy local scan" and "mopdyctl local scan", in both cases scan finished successfully but i could not access the library in any web-frontend (tried muse, musicbox and iris). 

however after uncommenting these lines in the config it worked for some reason:

```
[core]
cache_dir = $XDG_CACHE_DIR/mopidy
config_dir = $XDG_CONFIG_DIR/mopidy
data_dir = $XDG_DATA_DIR/mopidy
```

**Comment by diabl0w** [comment]
if using iris, look at jaedb's replies here:
https://github.com/jaedb/Iris/issues/646

**Comment by bendschs** [comment]
i have done that multiple times (refreshing). guess there was something messed up with database.
