### ISSUE TITLE
Compiling for nanoPi M4 (AArch64) – How?

### ISSUE THREAD

**Issue by Wookbert** [mopidy/mopidy-local#56]
I'm trying to install mopidy-local on my FriendlyARM [nanoPi M4](https://wiki.friendlyarm.com/wiki/index.php/NanoPi_M4v2) via `python3 -m pip install mopidy-local` but get the following compilation error. Any ideas how to fix this?

![image](https://user-images.githubusercontent.com/3104762/104848623-36338300-58e6-11eb-9888-cf02a59d5d8c.png)

Same problem when compiling mopidy-headless:

![image](https://user-images.githubusercontent.com/3104762/104848634-477c8f80-58e6-11eb-8d3c-c3e480b58847.png)

Thanks in advance.

**Comment by dz0ny** [comment]
You are missing development libraries (apt install python3-dev build-essential). Also, look at https://discourse.mopidy.com/t/pyspotify-not-working-on-raspberry-pi-4-arm64-architecture/3885/8 if you plan to install Spotify.

**Comment by Wookbert** [comment]
@dz0ny Thanks for your swift reply. I've meanwhile been able to install mopidy-local and mopidy-headless, except for a minor error (below in red) on the latter:

![image](https://user-images.githubusercontent.com/3104762/104961841-71fa4580-59d7-11eb-9bbd-5c7e4667df54.png)

Problem now is that the server no longer starts (see below). Probably some config issues. Any hints?

![image](https://user-images.githubusercontent.com/3104762/104961915-a241e400-59d7-11eb-85dc-5350645a3cd9.png)

**Comment by dz0ny** [comment]
Please post these to discourse, or you might already find the answer there. Now to the issue, you are still missing some build dependencies (apt build-dep mopidy... should install proper deps if you have apt repo set). For config it looks like you added **;** somewhere you should not.
