### ISSUE TITLE
Not load from global config file

### ISSUE THREAD

**Issue by rickywu** [mopidy/mopidy-local#60]
I use /etc/mopidy/mopidy.conf, add these lines:

```
[local]
enabled = true
media_dir = var/lib/mopidy/xxx

```

and use mopidy local scan got

```
ERROR    2021-07-28 10:51:22,356 [900843:MainThread] mopidy.__main__
  Unable to run command provided by disabled extension local
```
and mopidy config got 

```
[local]
enabled = false  ; Extension disabled due to config errors.
max_search_results = 100
media_dir =  ; Must be set.
```

after add to ~/.config/mopidy/mopidy.config and run mopidy local scan without errors

**Comment by kingosticks** [comment]
The two different ways to run Mopidy are documented at https://docs.mopidy.com/en/latest/running/

You've mixed two methods and as a result have edited the wrong config file for the way you're running.
