### ISSUE TITLE
'mopidy local scan' is using the wrong config file

### ISSUE THREAD

**Issue by ChrisZ32** [mopidy/mopidy-local#67]
I run mopidy as a service, so my config is located in `/etc/mopidy/mopidy.conf`.

However, `mopidy local scan` is reading config from the ` /home/pi/.config/mopidy/mopidy.conf` file.

`mopidy local scan` should be using the actual config loaded into mopidy instead.

**Comment by kingosticks** [comment]
You should use `sudo mopidyctl local scan` when running as a service. This is explained at https://docs.mopidy.com/en/latest/running/service/
