### ISSUE TITLE
Add support for embedded album art in local / network files

### ISSUE THREAD

**Issue by drewdah** [mopidy/mopidy-local#7]
I'm very new to mopidy (using via PiMusicbox right now), but while trying to build a small "now playing" frontend for low resolution LCD screens on the raspberry pi I noticed that mopidy doesn't seem to read album artwork that is embedded in local files. 

PiMusicbox appears to rely on a request to a last.fm library to pull in the album artwork, but that could be avoided if the artwork is embedded in the file.

Would it be possible add support for reading embedded artwork from the ID3 tag and passing that in the album model as a data URI?

**Comment by tkem** [comment]
Since `mopidy-local-sqlite` and `mopidy-local-images` will effectively merge into `mopidy-local` for Mopidy v3.0, yes, it is on the roadmap.

**Comment by jodal** [comment]
They have been merged, so this should be fixed once we release 3.0 this weekend.

**Comment by AryToNeX** [comment]
how can we toggle this feature on? Is it on by default? I have my whole collection of flac music without album arts displayed!
