### ISSUE TITLE
Folder directory

### ISSUE THREAD

**Issue by cuthulino** [mopidy/mopidy-local#76]
Hello,

I use mopidy-local together with mopidy-iris.
Everything works very well but I am missing something I thougth it was there.

A "Folder" directory to browse the folder structure.
Is there a possibility to get it?

![grafik](https://github.com/mopidy/mopidy-local/assets/4634522/4a6e9beb-4016-4b92-ba14-45fcfdc3d924)

**Comment by kingosticks** [comment]
No, it's not there. Mopidy-File extension provides this: https://docs.mopidy.com/en/latest/ext/file/#mopidy-file
